# Generated by Django 3.0.5 on 2020-05-05 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200505_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='permission',
            name='desc',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='user',
            name='add_date',
            field=models.DateTimeField(auto_now=True, verbose_name='user add date'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teamrole',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('In-Active', 'In-Active')], max_length=20),
        ),
    ]
